### ISSUE TITLE
"Tilbake til oversikt" will not work if users are following link to specific event.

### ISSUE THREAD

**Issue by martinegeli** [dagsfylla/dagsfylla#32]
- If partypeople use link to detailview of event, possibly sent over messenger, the "Tilbake til oversikt" will send partypeople to blank page.

**Comment by ankile** [comment]
Fantastic point, I’ll fix later today if you don’t fix it first :)

**Comment by martinegeli** [comment]
I´m going to my father in typical "dagsfylla" manners in short to no time, so the futures potential of "Tilbake til oversikt" fully depends on your extravagant powers.

**Comment by ankile** [comment]
Of course, I understand. I have now resolved the issue. Please have yourself a jolly good time with your kin today.
